/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.SanPhamLoi;
import ServiceInterface.ImanageSanPhamLoiService;
import ServiceImplement.SanPhamLoiService;
import ViewModel.QLSanPhamLoi;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL 5515
 */
public class FormSanPhamLoi extends javax.swing.JFrame {

    private final ImanageSanPhamLoiService imanageSanPhamLoiService;

    public FormSanPhamLoi() {
        initComponents();
        imanageSanPhamLoiService = new SanPhamLoiService();
        loadTable();
        txtmaspl.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmaspl = new javax.swing.JTextField();
        cbomasach = new javax.swing.JComboBox<>();
        txtsl = new javax.swing.JTextField();
        txtlydo = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSPL = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã SPL");

        jLabel2.setText("Mã Sách");

        jLabel3.setText("Số lượng");

        jLabel4.setText("Lý do");

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        tblSPL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SPL", "Mã sách", "Số lượng", "Lý do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSPL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSPL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnadd)
                .addGap(68, 68, 68)
                .addComponent(btnupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btndelete)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtmaspl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbomasach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtlydo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtmaspl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cbomasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnupdate)
                    .addComponent(btndelete))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSPLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPLMouseClicked
        int row = tblSPL.getSelectedRow();
        if (row == -1) {
            return;
        }
        txtlydo.setText(tblSPL.getValueAt(row, 3).toString());
        txtmaspl.setText(tblSPL.getValueAt(row, 0).toString());
        txtsl.setText(tblSPL.getValueAt(row, 2).toString());
        String masach = tblSPL.getValueAt(row, 1).toString();

        cbomasach.setSelectedItem(masach);
    }//GEN-LAST:event_tblSPLMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        SanPhamLoi sp = getdataFromInput();
//        if(txtmaspl.getText().trim().equalsIgnoreCase("")){
//         JOptionPane.showMessageDialog(this, "Vui lòng điền mã sản phẩm lỗi");
//         return;
//        }
        if (txtsl.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền số lượng");
            return;
        }
        if (txtlydo.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền lý do đổi");
            return;
        }

        if (imanageSanPhamLoiService.add(sp) != null) {
            JOptionPane.showMessageDialog(this, "Add thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Add thất bại");
            return;
        }
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int row = tblSPL.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng trên table để xóa");
            return;
        }
        String maspl = tblSPL.getValueAt(row, 0).toString();
        if (imanageSanPhamLoiService.delete(maspl) != null) {
            JOptionPane.showMessageDialog(this, "Delete thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Delete thất bại");
            return;
        }
        loadTable();
        clearForm();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        
//        if(txtmaspl.getText().trim().equalsIgnoreCase("")){
//         JOptionPane.showMessageDialog(this, "Vui lòng điền mã sản phẩm lỗi");
//         return;
//        }
        int row = tblSPL.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng trên table để cập nhật");
         return;
        }
        
                
        if (txtsl.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền số lượng");
            return;
        }
        if (txtlydo.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền lý do đổi");
            return;
        }

        SanPhamLoi sp = getdataFromInput();
        String maspl = tblSPL.getValueAt(row, 0).toString();
        if (imanageSanPhamLoiService.update(maspl, sp) != null) {
            JOptionPane.showMessageDialog(this, "Update thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Update thất bại");
            return;
        }
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSanPhamLoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSanPhamLoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSanPhamLoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSanPhamLoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSanPhamLoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbomasach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSPL;
    private javax.swing.JTextField txtlydo;
    private javax.swing.JTextField txtmaspl;
    private javax.swing.JTextField txtsl;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        
        List<QLSanPhamLoi> list = imanageSanPhamLoiService.getAll();

        DefaultTableModel tblmodel = (DefaultTableModel) tblSPL.getModel();
        tblmodel.setRowCount(0);
        
        for (QLSanPhamLoi sp : list) {
            tblmodel.addRow(new Object[]{sp.getMaSPL(), sp.getMaSach(), sp.getSoLuong(), sp.getLyDoDoi()});
        }
    }

    private void clearForm() {
        txtlydo.setText("");
        txtmaspl.setText("");
        txtsl.setText("");
    }

    private SanPhamLoi getdataFromInput() {
        SanPhamLoi sp = new SanPhamLoi();
        sp.setLyDoDoi(txtlydo.getText());
        try {
            sp.setMaSPL(Integer.parseInt(txtmaspl.getText()));
            sp.setMaSach(Integer.parseInt(cbomasach.getSelectedItem().toString()));
            sp.setSoLuong(Integer.parseInt(txtsl.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }

        return sp;
    }
}
